### ISSUE TITLE
Congrats! but, does it work also for WhatsApp?

### ISSUE THREAD

**Issue by consultfiv** [richpauloo/textme#1]
Congrats for this initiative!! I didn't imagine that it could be done also in R. 
Is it possible to send WhatsApp messages also? Or is it only for SMS?

**Comment by richpauloo** [comment]
This function works with SMS, and should be able to expand to WhatsApp since twilio supports this (https://www.twilio.com/whatsapp).

You should also check out Sean Kross' `{twilio}` R package: https://github.com/seankross/twilio, which this package uses to just make it easier to text yourself silly messages.
